/* eslint-disable import/prefer-default-export */
import React from 'react';
import tripbg from 'static/images/shop-categories/merchant-imgs-logos/trip.jpg';
import tripicon from 'static/images/shop-categories/merchant-imgs-logos/trip-logo.png';
import { FormattedMessage } from 'react-intl';

export const adds = [
  {
    cashbackText: <FormattedMessage id="data.upto" />,
    cahsback: '2.4%',
    tlc: '1.23',
    bgImg: 'images/card/alibaba.jpg',
    icon: 'images/card/alibaba-logo.png',
    offerType: <FormattedMessage id="data.headermyearningsvipcashback" />,
    tlcText: 'TLC',
  },
  {
    cashbackText: <FormattedMessage id="data.upto" />,
    cahsback: '0.4%',
    tlc: '2 ',
    bgImg: 'images/card/emirates.jpg',
    icon: 'images/card/emirate-logo.png',
    offerType: <FormattedMessage id="data.headermyearningsvipcashback" />,
    tlcText: 'TLC',
  },
  {
    cashbackText: <FormattedMessage id="data.upto" />,
    cahsback: '4%',
    tlc: '2 ',
    bgImg: 'images/card/expedia.jpg',
    icon: 'images/card/epedia-logo.png',
    offerType: <FormattedMessage id="data.headermyearningsvipcashback" />,
    tlcText: 'TLC',
  },
  {
    cashbackText: <FormattedMessage id="data.upto" />,
    cahsback: '1.4%',
    tlc: '0.7 ',
    bgImg: 'images/card/goto.jpg',
    icon: 'images/card/goto-logo.png',
    offerType: <FormattedMessage id="data.headermyearningsvipcashback" />,
    tlcText: 'TLC',
  },
  {
    cashbackText: <FormattedMessage id="data.upto" />,
    cahsback: '2.4%',
    tlc: '1.2 ',
    bgImg: 'images/card/hotel.jpg',
    icon: 'images/card/hotel-logo.png',
    offerType: <FormattedMessage id="data.headermyearningsvipcashback" />,
    tlcText: 'TLC',
  },
  {
    cashbackText: <FormattedMessage id="data.upto" />,
    cahsback: '2.4%',
    tlc: '1.2 ',
    bgImg: 'images/card/parkplaza.jpg',
    icon: 'images/card/park-plaza-logo.png',
    offerType: <FormattedMessage id="data.headermyearningsvipcashback" />,
    tlcText: 'TLC',
  },
];

export const addsDemo = [
  {
    cashbackText: <FormattedMessage id="data.upto" />,
    cahsback: '2.4%',
    tlc: '1.23',
    bgImg: 'images/card/alibaba.jpg',
    icon: 'images/card/alibaba-logo.png',
    offerType: <FormattedMessage id="data.headermyearningsvipcashback" />,
    tlcText: 'TLC',
  },
  {
    cashbackText: <FormattedMessage id="data.upto" />,
    cahsback: '0.4%',
    tlc: '2',
    bgImg: 'images/card/emirates.jpg',
    icon: 'images/card/emirate-logo.png',
    offerType: <FormattedMessage id="data.headermyearningsvipcashback" />,
    tlcText: 'TLC',
  },
  {
    cashbackText: <FormattedMessage id="data.upto" />,
    cahsback: '4%',
    tlc: '2',
    bgImg: 'images/card/expedia.jpg',
    icon: 'images/card/epedia-logo.png',
    offerType: <FormattedMessage id="data.headermyearningsvipcashback" />,
    tlcText: 'TLC',
  },
  {
    cashbackText: <FormattedMessage id="data.upto" />,
    cahsback: '1.4%',
    tlc: '0.7',
    bgImg: 'images/card/goto.jpg',
    icon: 'images/card/goto-logo.png',
    offerType: <FormattedMessage id="data.headermyearningsvipcashback" />,
    tlcText: 'TLC',
  },
  {
    cashbackText: <FormattedMessage id="data.upto" />,
    cahsback: '2.4%',
    tlc: '1.2',
    bgImg: 'images/card/hotel.jpg',
    icon: 'images/card/hotel-logo.png',
    offerType: <FormattedMessage id="data.headermyearningsvipcashback" />,
    tlcText: 'TLC',
  },
  {
    cashbackText: <FormattedMessage id="data.upto" />,
    cahsback: '2.4%',
    tlc: '1.2',
    bgImg: 'images/card/parkplaza.jpg',
    icon: 'images/card/park-plaza-logo.png',
    offerType: <FormattedMessage id="data.headermyearningsvipcashback" />,
    tlcText: 'TLC',
  },

  {
    cashbackText: <FormattedMessage id="data.upto" />,
    cahsback: '2.4%',
    tlc: '1.2',
    bgImg: 'images/shop-categories/merchant-imgs-logos/trip.jpg',
    icon: 'images/shop-categories/merchant-imgs-logos/trip-logo.png',
    offerType: <FormattedMessage id="data.headermyearningsvipcashback" />,
    tlcText: 'TLC',
  },
  {
    cashbackText: <FormattedMessage id="data.upto" />,
    cahsback: '3.2%',
    tlc: '1.6',
    bgImg: 'images/shop-categories/merchant-imgs-logos/sephoro.jpg',
    icon: 'images/shop-categories/merchant-imgs-logos/sephoro.png',
    offerType: <FormattedMessage id="data.headermyearningsvipcashback" />,
    tlcText: 'TLC',
  },
  {
    cashbackText: <FormattedMessage id="data.upto" />,
    cahsback: '3.5%',
    tlc: '1.7',
    bgImg: 'images/shop-categories/merchant-imgs-logos/nike.jpg',
    icon: 'images/shop-categories/merchant-imgs-logos/nike.png',
    offerType: <FormattedMessage id="data.headermyearningsvipcashback" />,
    tlcText: 'TLC',
  },
  {
    cashbackText: <FormattedMessage id="data.upto" />,
    cahsback: '1%',
    tlc: '0.5',
    bgImg: 'images/shop-categories/merchant-imgs-logos/etihad-log.jpg',
    icon: 'images/shop-categories/merchant-imgs-logos/etihad-log.png',
    offerType: <FormattedMessage id="data.headermyearningsvipcashback" />,
    tlcText: 'TLC',
  },
  {
    cashbackText: <FormattedMessage id="data.upto" />,
    cahsback: '2.4%',
    tlc: '1.2',
    bgImg: 'images/shop-categories/merchant-imgs-logos/agoda.jpg',
    icon: 'images/shop-categories/merchant-imgs-logos/agoda.png',
    offerType: <FormattedMessage id="data.headermyearningsvipcashback" />,
    tlcText: 'TLC',
  },
  {
    cashbackText: <FormattedMessage id="data.upto" />,
    cahsback: '$7',
    tlc: '7',
    bgImg: 'images/shop-categories/merchant-imgs-logos/cheap0air.jpg',
    icon: 'images/shop-categories/merchant-imgs-logos/cheap0air.png',
    offerType: <FormattedMessage id="data.headermyearningsvipcashback" />,
    tlcText: 'TLC',
  },
];

export const members = [
  {
    image: 'icons-images/refer.jpg',
    btnText: <FormattedMessage id="data.HPreferafriend" />,
    class: 'big-img',
    url: '/refer-friend',
  },
  {
    image: 'icons-images/vip.png',
    btnText: <FormattedMessage id="data.HPbecomevip" />,
    class: 'small-img',
    url: '/vip-benefits',
  },
];

export const featureAdds = [
  {
    cashbackText: <FormattedMessage id="data.upto" />,
    cahsback: '4%',
    tlc: '2 ',
    bgImg: 'images/card/expedia.jpg',
    icon: 'images/card/epedia-logo.png',
    offerType: <FormattedMessage id="data.headermyearningsvipcashback" />,
    tlcText: 'TLC',
  },
  {
    cashbackText: <FormattedMessage id="data.upto" />,
    cahsback: '2.4%',
    tlc: '1.2',
    bgImg: 'images/shop-categories/merchant-imgs-logos/trip.jpg',
    icon: 'images/shop-categories/merchant-imgs-logos/trip-logo.png',
    offerType: <FormattedMessage id="data.headermyearningsvipcashback" />,
    tlcText: 'TLC',
  },
  {
    cashbackText: <FormattedMessage id="data.upto" />,
    cahsback: '3.5%',
    tlc: '1.75',
    bgImg: 'images/shop-categories/merchant-imgs-logos/nike.jpg',
    icon: 'images/shop-categories/merchant-imgs-logos/nike.png',
    offerType: <FormattedMessage id="data.headermyearningsvipcashback" />,
    tlcText: 'TLC',
  },
  {
    cashbackText: <FormattedMessage id="data.upto" />,
    cahsback: '2.4%',
    tlc: '1.2',
    bgImg: 'images/shop-categories/merchant-imgs-logos/agoda.jpg',
    icon: 'images/shop-categories/merchant-imgs-logos/agoda.png',
    offerType: <FormattedMessage id="data.headermyearningsvipcashback" />,
    tlcText: 'TLC',
  },
];
export const TLCdeals = [
  {
    cashbackText: 'Price',
    cahsback: '$11',
    tlc: '25%',
    bgImg: 'images/shop-categories/shirt.jpg',
    // icon: expediaLogo,
    offerType: 'Sprout',
    tlcText: 'Pay in TLC',
  },
  {
    cashbackText: 'Price',
    cahsback: '$2.4',
    tlc: '40%',
    bgImg: 'images/shop-categories/food.jpg',
    // icon: tripicon,
    offerType: 'Taste Factory',
    tlcText: 'Pay in TLC',
  },
  {
    cashbackText: 'Price',
    cahsback: '$350',
    tlc: '20%',
    bgImg: 'images/shop-categories/cwj.jpg',
    // icon: nikeicon,
    offerType: 'CWJ',
    tlcText: 'Pay in TLC',
  },
  {
    cashbackText: 'Price',
    cahsback: '$220',
    tlc: '10%',
    bgImg: 'images/shop-categories/Warsi.jpg',
    // icon: agodaicon,
    offerType: 'Warsi E Services',
    tlcText: 'Pay in TLC',
  },
];
