export default {
  'en-US': {
    data: {
      headermyearningsexchange: 'Current Exchange Rate',
      menuHPcashbackworks: 'HOW CASH BACK WORKS',
      HPcategories: 'CATEGORIES',
      filterboxSCflatrate: 'Flat Rate',
      HPfriendsshopping: 'Friends Shopping Network',
      headermyearningsrfreferralbonus: 'Referral Bonus',
      headermyearningsreward: 'You will receive $5 and 5 TLC when you save $25 in paid Cash Back.',
      filterboxSCcashback: 'Cash Back %',
      HPselectcountry: 'Select Country',
      booknow: 'BOOK NOW',
      headercusubtitle: 'Have feedback or need some help?',
      filterboxSCdealtype: 'DEAL TYPE',
      HPbrands: 'BRANDS',
      headermyearningsrfpotentialtlc: 'Potential TLC Reward',
      formcumessage: 'Message',
      filterboxSCsalesoffer: 'Sales Offers',
      headermyearningsrffriendsnetwork: 'YOUR FRIENDS NETWORK',
      sortmenuSCall: 'All',
      copymyearningsvipcontent:
        'You are a VIP10 Member and qualify to receive 10% …receive bonuses of your Cash Back and TLC Reward.',
      fieldsufriend: 'Friend',
      HPfashion: 'Fashion',
      headerhcearnextra: 'EARN EXTRA REWARDS',
      headermyearningspaid: 'Paid',
      copysuprivacypolicy: 'I agree to the Terms & Conditions and Privacy Policy.',
      HPbecomevip: 'Become A VIP',
      headermyearningspending: 'Pending',
      fieldlpenterpassword: 'Enter password',
      headermyearningsviporderid: 'Order ID',
      sortmenuSCcoupons: 'Coupons',
      headermyearningsvipbupgradedate: 'VIP Upgrade Date',
      HPdealscashback: 'Discover Even More Deals With Cash Back',
      headermyearningsfriendshipbonus: 'FRIENDSHIP BONUS',
      HPfooterpopularlinks: 'POPULAR LINKS',
      headermyearningsvipbvipbonus: 'VIP Bonus',
      HPshopnow: 'SHOP NOW',
      headermyearningsviptlcreward: 'TLC REWARD',
      buttonlplogin: 'LOGIN',
      buttonvb: 'JOIN VIP REWARDS TODAY',
      sortbymenuSC: 'Sort By',
      headerhcwhatiscashback: 'WHAT IS CASH BACK?',
      copyrfsharereferral: 'Share your referral link below',
      headermyearningsrfcashbackpending: 'Cash Back Pending',
      copyabovefriendshipbonusfriendshipbonus: 'Friendship Bonus Tier 5%',
      headermyearnings: 'You have qualified for a Welcome Gift',
      headermyearningsvipqualifiedwelcomegift: 'Name',
<<<<<<< HEAD
      copyabovefriendshipbonusfriendshipbonus2: 'You qualify for 20% Friendship Bonus',
=======
      copyabovefriendshipbonusfriendshipbonus1: 'You qualify for 20% Friendship Bonus',
>>>>>>> a3f21cdd29268a6c505809260221bfe6442982d3
      headercusubheading: 'Have feedback or need some help?',
      headermyearningsvipbusername: 'Username',
      headermyearningswelcomegift: 'WELCOME GIFT',
      HPfinance: 'Finance',
      copymyearningsvip5: 'You Qualify for 5% VIP Cash Back',
      headercuintouch: 'GET IN TOUCH',
      headermyearningsvipdeclined: 'Declined',
      copymyearningsvipbcontent:
        'You will receive $5 and 5 TLC when your referred f… limit to the amount of VIP Bonuses you can earn.',
      filterboxSCtlcdeal: 'TLC Deal',
      headermyearningsvippaid: 'Paid',
      headermyearningsname: 'Name',
      fieldlpenterusername: 'Enter username',
      copyrfsendusername: 'Send your username',
      buttonrfusername6degree: 'username.6Degrees.CASH',
      copyabovefriendshipbonusfriendshipbonus1: 'You qualify for 10% Friendship Bonus',
      copymyearningsrf5:
        'You will receive $5 and 5 TLC for helping your fri…f Referral Bonuses you can earn.  Keep Referring!',
      BannerSC: 'SHOP CATEGORIES',
      fieldsu2name: 'name',
      copylpforgotpassword: 'Forgot Password',
      copymyearningsvip20: 'Do you want to qualify for 20% VIP Cash Back?',
      copyabovefriendshipbonusfriendshipbonus10member:
        'You are a VIP10 Member and qualify to receive 10% …ip Bonus up to 6 Degrees of your friends network.',
      copyabovefriendshipbonusfriendshipbonusearningcalculator: 'Earning Calculator',
      fieldsu2username: 'username',
      fieldsuselecvt: 'Select',
      headermyearningsreferealbonus: 'REFERRAL BONUS',
      headermyearningsrfsignups: 'Signups',
      HPseeall: 'SEE ALL',
      copylp: 'Enter your personal details to begin earning CashBack.',
      copyabovefriendshipbonusfriendshipbonus20:
        'Help twenty friends to become VIP Members and you qualify for 20% Friendship Bonus.',
      HPcashbackoffers: 'CASH BACK OFFERS',
      boxhcbonusprogram: 'Refer A Friend Bonus Program',
      headermyearningsrffrineds: 'Friends',
      copyrfreferafriend:
        'Refer a Friend is to be used for recommending 6Deg…ctronic communications if you have their consent.',
      copymyearningsvipvip20:
        'You are a VIP20 Member and qualify to receive 20% …receive bonuses of your Cash Back and TLC Reward.',
      copyabovefriendshipbonusfriendshipbonusteamdetails: 'Team Details',
      headermyearningsvippending: 'Pending',
      headermyearningsvipbonus: 'VIP BONUS',
      HPcode: 'CODE',
      headermyearningsvipfilter: 'FILTER',
      copyabovefriendshipbonusfriendshipbonustotalfriends: 'Total Friends Team',
      copyabovefriendshipbonusfriendshipbonus5: 'You qualify for 5% Friendship Bonus',
      headermyearningsoffernumber: 'Offer #',
      menuHPshopcategories: 'SHOP CATEGORIES',
      boxrf$5:
        'You will receive $5 and 10 TLC for helping your fr…his Referral Bonus, keep spreading the good word.',
      menuHPcapsrefer: 'REFER A FRIEND',
      headermyearningsrftermsconditions: 'Terms & Conditions Apply *',
      headermyearningsvipbtlcreward: 'TLC Reward',
      filterboxSCfeaturedmarchant: 'Featured Merchant',
      HPsearchbystore: 'Search by Store',
      filterboxSConline: 'Online',
      headermyearningsvipviptier: 'VIP Tier',
      boxhcshop: 'Shop',
      headermyearningsvipmerchant: 'MERCHANT',
      HPtravel: 'Travel',
      copyrfshareonsocialmedia: 'Share on Social Media',
      HPelectronics: 'Electronics',
      copyabovefriendshipbonusfriendshipbonuspaid: 'Total Friendship Bonus Paid',
      headermyearningsvipbtermsconditions: 'Terms & Conditions Apply *',
      copysu2username: 'username',
      headermyearningsvipvipcashback: 'VIP CASH BACK',
      copymyearningsvip20: 'You Qualify for 20% Cash Back',
      HPjoinfree: 'JOIN FREE',
      headermyearningspaymentperiod: 'Payment Period',
      filterboxSCsericearea: 'SERVICE AREA',
      boxhcreferbonusprogram: 'Refer A Friend Bonus Program',
      headerrf: 'THREE WAYS FOR YOU TO HELP YOUR FRIENDS SAVE MONEY',
      menuHPmyaccount: 'MY ACCOUNT',
      sortmenuSCcashbacktlc: 'CASH BACK + TLC',
      headermyearningsvipbsignups: 'Signups',
      copymyearningsrf:
        'Track the Cash Back performance of your friends. C…elp them save while earning your Referral Bonuses',
      headerlp: 'Hello Friend!',
      filterboxSCselectcountry: 'Select Country',
      HPhotdeals: 'HOT DEALS',
      headermyearningsrftlcreward: 'TLC Reward',
      copyabovefriendshipbonusfriendshipbonusyouareavip:
        'You are a VIP Member and qualify to receive 5% Fri…ip Bonus up to 6 Degrees of your friends network.',
      copyabovefriendshipbonusmyearningsvipb:
        'Track the VIP Upgrade status of your friends. Cont…em unlock VIP Benefits while earning VIP Bonuses.',
      copysu: 'How did you hear about us?',
      headermyearningsdeclined: 'Declined',
      headermyearningsvipcashback: 'CASH BACK',
      headermyearningsfilter: 'FILTER',
      sortmenuSCCashBack: 'CASH BACK',
      headermyearningssortby: 'SORT BY',
      headermyearningsvipoffernumber: 'Offer Number',
      formcu: 'NAME',
      headermyearningsvipbyourfriendsnetwork: 'YOUR FRIENDS NETWORK',
      headermyearningsvipbpotemtialtlc: 'Potential TLC Reward',
      headermyearningsrfpotentialreferalbonus: 'Potential Referral Bonus',
      boxrftrack:
        'You can track invitations and savings performance … Go to My Account > My Earnings > Referral Bonus.',
      boxhcbrowse: 'Browse',
      copysu2: 'My friend who referred me',
      headermyearningstlcreward: 'TLC REWARD',
      HPreferafriend: 'Refer A Friend',
      filterboxSCexlusiveoffers: 'Exclusive Offers',
      headermyearningsdate: 'DATE',
      copyabovefriendshipbonusfriendshipbonusqualify20:
        'Do you want to qualify for 20% Friendship Bonus?',
      fieldsuchooseusername: 'Choose username',
      headermyearningsrfjoindate: 'Join Date',
      boxrf$100:
        'Help your friends join 6Degrees free of cost and s…oney. On average one may save over $100 per year.',
      copymyearningsvip:
        'You are a VIP Member and qualify to receive 5% VIP…receive bonuses of your Cash Back and TLC Reward.',
      headermyearningsvipoverview: 'OVERVIEW',
      headermyearningsterms: 'Terms & Conditions',
      menuHP: 'VIP EVENTS',
      copymyearningsvipvipmember:
        'You are a VIP Member and qualify to receive 5% VIP…receive bonuses of your Cash Back and TLC Reward.',
      copyabovefriendshipbonusfriendshipbonus10:
        'Help ten friends to become VIP Members and you qualify for 10% Friendship Bonus.',
      bannerrf: 'Help Your Friends Save And You Get A Referral Bonus',
      HPnews: 'NEWS',
      headermyearningsvip: 'DATE',
      HPsubscribe: 'SUBSCRIBE NOW',
      headermyearningsvipbpotentialvip: 'Potential VIP Bonus',
      copyabovefriendshipbonusfriendshipbonus:
        'You are a VIP20 Member and qualify to receive 20% …ip Bonus up to 6 Degrees of your friends network.',
<<<<<<< HEAD
      copymyearningsvip10: 'Do you want to qualify for 10% VIP Cash Back?',
=======
      copymyearningsvip: 'Do you want to qualify for 10% VIP Cash Back?',
>>>>>>> a3f21cdd29268a6c505809260221bfe6442982d3
      boxhc: 'Earn Cash Back',
      headerhc: 'HOW DOES CASH BACK WORK?',
      fieldsuselectcountry: 'Select Country',
      filterboxSCinstore: 'InStore',
      fieldsu: 'Create Password',
      HPBanner: 'JOIN 6 DEGREES FOR FREE AND GET A $5 BONUS',
      headermyearningsrf: 'OVERVIEW',
      boxrf: 'TRACK PERFORMANCE',
      filterboxSC: 'SPECIAL',
      headermyearningsorderid: 'Order ID',
      headermyearningscashback: 'CASH BACK',
      headermyearningsvipb: 'Friends',
      sortmenuSC: 'Coupons',
      HPhealth: 'Health & Beauty',
      boxrfbonus: 'EARN REFERRAL BONUS',
      formcuemail: 'EMAIL',
      copylpstayloggedin: 'Stay Logged In',
      headermyearningsvipcashback: 'VIP CASH BACK',
      HPenteryouremail: 'Enter Your Email',
      filterboxSCglobal: 'Global',
      buttonsujoinfree: 'JOIN FREE',
      headermyearningspurchase: 'PURCHASE',
      buttonrfusername: 'Username',
      copymyearningsviphelp:
        'Help 20 friends to become VIP Members and you qualify for 20% VIP Cash Back.',
      boxrfinvite: 'INVITE YOUR FRIENDS',
      copymyearningsvipqualify: 'You Qualify for 10% Cash Back',
      headerhcearnextra: 'EARN EXTRA REWARDS',
      headermyearningsrfcashbackpaid: 'Cash Back Paid',
      fieldsusocialmedia: 'Social Media',
      copyrfrefreal:
        'To receive your Referral Bonus, the person you have referred must earn $25 payable cash back or more',
      copyabovefriendshipbonusfriendshipbonus: 'Do you want to qualify for 10% Friendship Bonus?',
      HPtitletopcoupons: "TODAY'S TOP COUPONS & OFFERS",
      headermyearningsvipbvip: 'VIP',
      filterboxSCmerchant: 'MERCHANT TYPE',
      boxhcgetpaid: 'GET PAID TO SHARE',
<<<<<<< HEAD
      welcomepackage: 'Welcome package',
=======
>>>>>>> a3f21cdd29268a6c505809260221bfe6442982d3
    },
  },
  'zh-CN': {
    data: {
      headermyearningsexchange: '当前的汇率',
      menuHPcashbackworks: '返现如何使用',
      HPcategories: '类别',
      filterboxSCflatrate: '平率',
      HPfriendsshopping: '好友网络购物',
      headermyearningsrfreferralbonus: '推荐奖金',
      headermyearningsreward: '您将收到5元和5 TLC当您节省25元现金回来。',
      filterboxSCcashback: '返现%',
      HPselectcountry: '选择国家',
      booknow: '有反馈还是需要帮助?',
<<<<<<< HEAD
      headercusubtitle: '交易类型',
      filterboxSCdealtype: '品牌',
      HPbrands: '潜在的TLC奖励',
      headermyearningsrfpotentialtlc: '消息',
      formcumessage: '销售提供',
      filterboxSCsalesoffer: '你的朋友网络',
      headermyearningsrffriendsnetwork: '所有',
      sortmenuSCall:
        '您是VIP会员，并有资格获得10%的VIP现金返还。继续存钱，你将继续收到现金返还和TLC奖励的奖金。',
      copymyearningsvipcontent: '朋友',
      fieldsufriend: '时尚',
      HPfashion: '获得额外奖励?',
      headerhcearnextra: '已付款',
      copysuprivacypolicy: '本人同意有关条款及细则及私隐政策。',
      HPbecomevip: '变成一个VIP',
      //    header-myearnings:'待定',
      fieldlpenterpassword: '输入密码',
      headermyearningsviporderid: '订单ID',
      sortmenuSCcoupons: '优惠券',
      headermyearningsvipbupgradedate: 'VIP升级日期',
      HPdealscashback: '发现更多现金返还交易',
      headermyearningsfriendshipbonus: '友谊奖励',
      HPfooterpopularlinks: '流行链接',
      headermyearningsvipbvipbonus: 'VIP奖金',
      HPshopnow: '现在购物',
      headermyearningsviptlcreward: 'TLC奖励',
      buttonlplogin: '登陆',
      buttonvb: '现在加入VIP奖励',
      sortbymenuSC: '排序',
      headerhcwhatiscashback: '什么是现金返还?',
      copyrfsharereferral: '下面分享你的推荐链接',
      headermyearningsrfcashbackpending: '现金等待',
      copyabovefriendshipbonusfriendshipbonus: '友谊奖励等级5%。',
      headermyearnings: '你有资格得到一份欢迎礼物',
      headermyearningsvipqualifiedwelcomegift: '名字',
      copyabovefriendshipbonusfriendshipbonus1: '你有资格获得20%的友谊奖金',
      headercusubheading: '有反馈还是需要帮助?',
      headermyearningsvipbusername: '用户名',
      headermyearningswelcomegift: '用户名',
      welcomepackage: '欢迎礼包',
      HPfinance: '财务',
      copymyearningsvip5: '您有资格获得5%的VIP现金返还',
      headercuintouch: '取得联系?',
      headermyearningsvipdeclined: '拒绝',
      copymyearningsvipbcontent:
        '当您推荐的朋友升级为VIP会员时，您将获得5美元和5 TLC。您可以获得的VIP奖金数量没有限制',
      filterboxSCtlcdeal: 'TLC交易',
      headermyearningsvippaid: '支付',
      headermyearningsname: '名字',
      fieldlpenterusername: '输入用户名',
      copyrfsendusername: '发送你的用户名',
      buttonrfusername6degree: '用户名.6度.现金',
      copyabovefriendshipbonusfriendshipbonus1: '你有资格获得10%的友谊奖金',
      copymyearningsrf5:
        '您将收到5美元和5 TLC帮助您的朋友节省25美元现金回来。你可以获得的推荐奖金没有限制。保持参考!',
      BannerSC: '商店配别',
      fieldsu2name: '名',
      copylpforgotpassword: '忘记密码',
      copymyearningsvip20: '您想获得20% VIP现金返还的资格吗?',
      copyabovefriendshipbonusfriendshipbonus10member:
        '您是VIP10会员，并有资格获得10%的友谊奖金高达6度您的朋友网络。',
      copyabovefriendshipbonusfriendshipbonusearningcalculator: '收入计算器。',
      fieldsu2username: '用户名',
      fieldsuselecvt: '选择',
      headermyearningsreferealbonus: '推荐奖金',
      headermyearningsrfsignups: '注册',
      HPseeall: '看全部',
      copylp: '输入你的个人信息，开始赚回现金。',
      copyabovefriendshipbonusfriendshipbonus20:
        '帮助二十个朋友成为VIP会员，你就有资格获得20%的友谊奖金。',
      HPcashbackoffers: '返现优惠',
      boxhcbonusprogram: '参考朋友奖励计划',
      headermyearningsrffrineds: '朋友',
      copyrfreferafriend:
        '推荐朋友是用来推荐6度的。把钱给你认识的人。只有在得到他人同意的情况下，你才可以通过电子邮件或其他电子通讯方式与他人联系。',
      copymyearningsvipvip20:
        '您是VIP会员，并有资格获得20% VIP现金返还。继续存钱，你将继续收到现金返还和TLC奖励的奖金。',
      copyabovefriendshipbonusfriendshipbonusteamdetails: '团队细节。',
      headermyearningsvippending: '等待',
      headermyearningsvipbonus: 'VIP奖励',
      HPcode: '代码',
      headermyearningsvipfilter: '过滤器',
      copyabovefriendshipbonusfriendshipbonustotalfriends: '朋友总团队。',
      copyabovefriendshipbonusfriendshipbonus5: '你有资格获得5%的友谊奖金。',
      headermyearningsoffernumber: '优惠#',
      menuHPshopcategories: '商店类别',
      boxrf$5:
        '您将收到5美元和10 TLC帮助您的朋友节省25美元。这是没有限制的推荐奖金，继续传播良好的口碑',
      menuHPcapsrefer: '推荐给一个朋友',
      headermyearningsrftermsconditions: '适用条款及细则*',
      headermyearningsvipbtlcreward: 'TLC奖励',
      filterboxSCfeaturedmarchant: '特色的商店',
      HPsearchbystore: '商店搜索',
      filterboxSConline: '线上',
      headermyearningsvipviptier: 'VIP级别',
      boxhcshop: '商店?',
      headermyearningsvipmerchant: '商人',
      HPtravel: '旅游',
      copyrfshareonsocialmedia: '在社交媒体上分享',
      HPelectronics: '电子产品',
      ccopyabovefriendshipbonusfriendshipbonuspaid: '友谊奖金总额。',
      headermyearningsvipbtermsconditions: '适用条款及细则*',
      copysu2username: '用户名',
      headermyearningsvipvipcashback: 'VIP现金返还',
      copymyearningsvip20: '您有资格获得20%的现金返还',
      HPjoinfree: '免费加入',
      headermyearningspaymentperiod: '付款期',
      filterboxSCsericearea: '服务区',
      boxhcreferbonusprogram: '参考朋友奖励计划',
      headerrf: '帮助你的朋友省钱的三种方法',
      menuHPmyaccount: '我的账户',
      sortmenuSCcashbacktlc: '返现+TLC',
      headermyearningsvipbsignups: '注册',
      copymyearningsrf:
        '跟踪你朋友的现金返还表现。联系你的朋友谁还没有开始赚钱回来，以帮助他们节省，同时赚取你的推荐奖金',
      headerlp: '你好朋友！',
      filterboxSCselectcountry: '选择国家',
      HPhotdeals: '最热优惠',
      headermyearningsrftlcreward: 'TLC奖励',
      copyabovefriendshipbonusfriendshipbonusyouareavip:
        '您是VIP会员，并有资格获得5%的友谊奖金高达6度您的朋友网络。。',
      copyabovefriendshipbonusmyearningsvipb:
        '跟踪您朋友的VIP升级状态。联系您的朋友谁还没有升级，以帮助他们解锁VIP优惠，同时赚取VIP奖金。',
      copysu: '如何知道我们的？',
      headermyearningsdeclined: '拒绝',
      headermyearningsvipcashback: '现金返还',
      headermyearningsfilter: '过滤器',
      sortmenuSCCashBack: '返现',
      headermyearningssortby: '订单数量',
      formcu: '名字',
      headermyearningsvipbyourfriendsnetwork: '你的朋友网络',
      headermyearningsvipbpotemtialtlc: '潜在的TLC奖励',
      headermyearningsrfpotentialreferalbonus: '潜在的推荐奖金',
      boxrftrack: '你可以跟踪你朋友的邀请和储蓄表现。到我的帐户>我的收入>推荐奖金。',
      boxhcbrowse: '浏览?',
      copysu2: '推荐我的那位朋友',
      headermyearningstlcreward: 'TLC奖励',
      HPreferafriend: '推荐一个朋友',
      filterboxSCexlusiveoffers: '独家提供',
      headermyearningsdate: '日期',
      copyabovefriendshipbonusfriendshipbonusqualify20: '你想获得20%的友谊奖金吗?',
      fieldsuchooseusername: '选择用户名',
      headermyearningsrfjoindate: '加入日期',
      boxrf$100: '帮助你的朋友加入6度免费，并开始省钱。平均每人每年可以节省100多美元',
      copymyearningsvip:
        '您是VIP会员，并有资格获得5%的VIP现金返还。继续存钱，你将继续收到现金返还和TLC奖励的奖金。',
      headermyearningsvipoverview: '概述',
      headermyearningsterms: '条款和条件',
      menuHP: 'VIP活动',
      copymyearningsvipvipmember:
        '您是VIP会员，并有资格获得5%的VIP现金返还。继续存钱，你将继续收到现金返还和TLC奖励的奖金。',
      copyabovefriendshipbonusfriendshipbonus10:
        '帮助十个朋友成为VIP会员，你就有资格获得10%的友谊奖金',
      bannerrf: '帮助你的朋友省钱，你就能得到推荐奖金',
      HPnews: '新闻',
      headermyearningsvip: '日期',
      HPsubscribe: '现在订阅',
      headermyearningsvipbpotentialvip: '潜在的VIP奖金',
      copyabovefriendshipbonusfriendshipbonus:
        '您是VIP20会员，并有资格获得20%的友谊奖金高达6度您的朋友网络。',
      copymyearningsvip10: '您想获得10%的VIP现金返还吗?',
      boxhc: '获得现金返还?',
      headerhc: '现金返还是如何运作的?',
      fieldsuselectcountry: '选择国家',
      filterboxSCinstore: '商店内',
      fieldsu: '创建密码',
      HPBanner: '加入6度免费，并获得5美元奖金',
      headermyearningsrf: '概述',
      boxrf: '跟踪性能',
      filterboxSC: '特殊的',
      headermyearningsorderid: '订单ID',
      headermyearningscashback: '现金返还',
      headermyearningsvipb: '朋友',
      sortmenuSC: '优惠券',
      HPhealth: '健康&美容',
      boxrfbonus: '获得推荐奖金',
      formcuemail: '电子邮件',
      copylpstayloggedin: '保持登陆',
      headermyearningsvipcashback: 'VIP现金返还',
      HPenteryouremail: '进入你的邮箱',
      filterboxSCglobal: '全球',
      buttonsujoinfree: '免费加入',
      headermyearningspurchase: '购买',
      buttonrfusername: '用户名',
      copymyearningsviphelp: '帮助20位朋友成为VIP会员，即可获得20% VIP现金返还。',
      boxrfinvite: '邀请你的朋友',
      copymyearningsvipqualify: '你有资格得到10%的现金返还',
      headerhcearnextra: '获得额外奖励?',
      headermyearningsrfcashbackpaid: '现金支付',
      fieldsusocialmedia: '社交传媒',
      copyrfrefreal: '要收到你的推荐奖金，你推荐的人必须赚回25美元或更多的现金',
      copyabovefriendshipbonusfriendshipbonus: '你想获得10%的友谊奖金吗?',
      HPtitletopcoupons: '今日优惠券&优惠',
      headermyearningsvipbvip: 'VIP',
      filterboxSCmerchant: '商店类型',
      boxhcgetpaid: '获得分享的报酬',
=======
      //    filter box-SC:'交易类型',
      //    undefined-HP:'品牌',
      //    header-myearningsrf:'潜在的TLC奖励',
      //    form-cu:'消息',
      //    filter box-SC:'销售提供',
      //    header-myearningsrf:'你的朋友网络',
      //    sort menu-SC:'所有',
      //    copy-myearningsvip:'您是VIP会员，并有资格获得10%的VIP现金返还。继续存钱，你将继续收到现金返还和TLC奖励的奖金。',
      //    field-su:'朋友',
      //    undefined-HP:'时尚',
      //    header-hc:'获得额外奖励?',
      //    header-myearnings:'已付款',
      //    copy-su:'本人同意有关条款及细则及私隐政策。',
      //    undefined-HP:'变成一个VIP',
      //    header-myearnings:'待定',
      //    field-lp:'输入密码',
      //    header-myearningsvip:'订单ID',
      //    sort menu-SC:'优惠券',
      //    header-myearningsvipb:'VIP升级日期',
      //    undefined-HP:'发现更多现金返还交易',
      //    header-myearnings:'友谊奖励',
      //    undefined-HP:'流行链接',
      //    header-myearningsvipb:'VIP奖金',
      //    undefined-HP:'现在购物',
      //    header-myearningsvip:'TLC奖励',
      //    button-lp:'登陆',
      //    button-vb:'现在加入VIP奖励',
      //    sort menu-SC:'排序',
      //    header-hc:'什么是现金返还?',
      //    copy-rf:'下面分享你的推荐链接',
      //    header-myearningsrf:'现金等待',
      //    copyabovefriendshipbonus-friendship-bonus:'友谊奖励等级5%。',
      //    header-myearnings:'你有资格得到一份欢迎礼物',
      //    header-myearningsvip:'名字',
      //    copyabovefriendshipbonus-friendship-bonus:'你有资格获得20%的友谊奖金',
      //    header-cu:'有反馈还是需要帮助?',
      //    header-myearningsvipb:'用户名',
      //    header-myearningsrf:'用户名',
      //    header-myearnings:'欢迎礼包',
      //    undefined-HP:'财务',
      //    copy-myearningsvip:'您有资格获得5%的VIP现金返还',
      //    header-cu:'取得联系?',
      //    header-myearningsvip:'拒绝',
      //    copy-myearningsvipb:'当您推荐的朋友升级为VIP会员时，您将获得5美元和5 TLC。您可以获得的VIP奖金数量没有限制',
      //    filter box-SC:'TLC交易',
      //    header-myearningsvip:'支付',
      //    header-myearnings:'名字',
      //    field-lp:'输入用户名',
      //    copy-rf:'发送你的用户名',
      //    button-rf:'用户名.6度.现金',
      //    copyabovefriendshipbonus-friendship-bonus:'你有资格获得10%的友谊奖金',
      //    copy-myearningsrf:'您将收到5美元和5 TLC帮助您的朋友节省25美元现金回来。你可以获得的推荐奖金没有限制。保持参考!',
      //    Banner-SC:'商店配别',
      //    field-su2:'名',
      //    copy-lp:'忘记密码',
      //    copy-myearningsvip:'您想获得20% VIP现金返还的资格吗?',
      //    copyabovefriendshipbonus-friendship-bonus:'您是VIP10会员，并有资格获得10%的友谊奖金高达6度您的朋友网络。',
      //    copyabovefriendshipbonus-friendship-bonus:'收入计算器。',
      //    field-su2:'用户名',
      //    field-su:'选择',
      //    header-myearnings:'推荐奖金',
      //    header-myearningsrf:'注册',
      //    undefined-HP:'看全部',
      //    copy-lp:'输入你的个人信息，开始赚回现金。',
      //    copyabovefriendshipbonus-friendship-bonus:'帮助二十个朋友成为VIP会员，你就有资格获得20%的友谊奖金。',
      //    undefined-HP:'返现优惠',
      //    box-hc:'参考朋友奖励计划',
      //    header-myearningsrf:'朋友',
      //    copy-rf:'推荐朋友是用来推荐6度的。把钱给你认识的人。只有在得到他人同意的情况下，你才可以通过电子邮件或其他电子通讯方式与他人联系。',
      //    copy-myearningsvip:'您是VIP会员，并有资格获得20% VIP现金返还。继续存钱，你将继续收到现金返还和TLC奖励的奖金。',
      //    copyabovefriendshipbonus-friendship-bonus:'团队细节。',
      //    header-myearningsvip:'等待',
      //    header-myearnings:'VIP奖励',
      //    undefined-HP:'代码',
      //    header-myearningsvip:'过滤器',
      //    copyabovefriendshipbonus-friendship-bonus:'朋友总团队。',
      //    copyabovefriendshipbonus-friendship-bonus:'你有资格获得5%的友谊奖金。',
      //    header-myearnings:'优惠#',
      //    menu-HP:'商店类别',
      //    box-rf:'您将收到5美元和10 TLC帮助您的朋友节省25美元。这是没有限制的推荐奖金，继续传播良好的口碑',
      //    menu-HP:'推荐给一个朋友',
      //    header-myearningsrf:'适用条款及细则*',
      //    header-myearningsvipb:'TLC奖励',
      //    filter box-SC:'特色的商店',
      //    undefined-HP:'商店搜索',
      //    filter box-SC:'线上',
      //    header-myearningsvip:'VIP级别',
      //    box-hc:'商店?',
      //    header-myearningsvip:'商人',
      //    undefined-HP:'旅游',

      //   copy-rf:'在社交媒体上分享',
      //   undefined-HP:'电子产品',
      // copyabovefriendshipbonus-friendship-bonus:'友谊奖金总额。',
      //   header-myearningsvipb:'适用条款及细则*',
      //   copy-su2:'用户名',
      //   header-myearningsvip:'VIP现金返还',
      //   copy-myearningsvip:'您有资格获得20%的现金返还',
      //   undefined-HP:'免费加入',
      //   header-myearnings:'付款期',
      //   filter box-SC:'服务区',
      //   box-hc:'参考朋友奖励计划',
      //   header-rf:'帮助你的朋友省钱的三种方法',
      //   menu-HP:'我的账户',
      //   sort menu-SC:'返现+TLC',
      //   header-myearningsvipb:'注册',
      //   copy-myearningsrf:'跟踪你朋友的现金返还表现。联系你的朋友谁还没有开始赚钱回来，以帮助他们节省，同时赚取你的推荐奖金',
      //   header-lp:'你好朋友！',
      //   filter box-SC:'选择国家',
      //   undefined-HP:'最热优惠',
      //   header-myearningsrf:'TLC奖励',
      //   copyabovefriendshipbonus-friendship-bonus:'您是VIP会员，并有资格获得5%的友谊奖金高达6度您的朋友网络。。',
      //   copyabovefriendshipbonus-myearningsvipb:'跟踪您朋友的VIP升级状态。联系您的朋友谁还没有升级，以帮助他们解锁VIP优惠，同时赚取VIP奖金。',
      //   copy-su:'如何知道我们的？',
      //   header-myearnings:'拒绝',
      //   header-myearningsvip:'现金返还',
      //   header-myearnings:'过滤器',
      //   sort menu-SC:'返现',
      //   header-myearnings:'排序',
      //   header-myearningsvip:'订单数量',
      //   form-cu:'名字',
      //   header-myearningsvipb:'你的朋友网络',
      //   header-myearningsvipb:'潜在的TLC奖励',
      //   header-myearningsrf:'潜在的推荐奖金',
      //   box-rf:'你可以跟踪你朋友的邀请和储蓄表现。到我的帐户>我的收入>推荐奖金。',
      //   box-hc:'浏览?',
      //   copy-su2:'推荐我的那位朋友',
      //   header-myearnings:'TLC奖励',
      //   undefined-HP:'推荐一个朋友',
      //   filter box-SC:'独家提供',
      //   header-myearnings:'日期',
      //   copyabovefriendshipbonus-friendship-bonus:'你想获得20%的友谊奖金吗?',
      //   field-su:'选择用户名',
      //   header-myearningsrf:'加入日期',
      //   box-rf:'帮助你的朋友加入6度免费，并开始省钱。平均每人每年可以节省100多美元',
      //   copy-myearningsvip:'您是VIP会员，并有资格获得5%的VIP现金返还。继续存钱，你将继续收到现金返还和TLC奖励的奖金。',
      //   header-myearningsvipb:'概述',
      //   header-myearnings:'条款和条件',
      //   menu-HP:'VIP活动',
      //   copy-myearningsvip:'您是VIP会员，并有资格获得5%的VIP现金返还。继续存钱，你将继续收到现金返还和TLC奖励的奖金。',
      //   copyabovefriendshipbonus-friendship-bonus:'帮助十个朋友成为VIP会员，你就有资格获得10%的友谊奖金',
      //   banner-rf:'帮助你的朋友省钱，你就能得到推荐奖金',
      //   undefined-HP:'新闻',
      //   header-myearningsvip:'日期',
      //   undefined-HP:'现在订阅',
      //   header-myearningsvipb:'潜在的VIP奖金',
      //   copyabovefriendshipbonus-friendship-bonus:'您是VIP20会员，并有资格获得20%的友谊奖金高达6度您的朋友网络。',
      //   copy-myearningsvip:'您想获得10%的VIP现金返还吗?',
      //   box-hc:'获得现金返还?',
      //   header-hc:'现金返还是如何运作的?',
      //   field-su:'选择国家',
      //   filter box-SC:'商店内',
      //   field-su:'创建密码',
      //   undefined-HP:'加入6度免费，并获得5美元奖金',
      //   header-myearningsrf:'概述',
      //   box-rf:'跟踪性能',
      //   filter box-SC:'特殊的',
      //   header-myearnings:'订单ID',
      //   header-myearnings:'现金返还',
      //   header-myearningsvipb:'朋友',
      //   sort menu-SC:'优惠券',
      //   undefined-HP:'健康&美容',
      //   box-rf:'获得推荐奖金',
      //   form-cu:'电子邮件',
      //   copy-lp:'保持登陆',
      //   header-myearnings:'VIP现金返还',
      //   undefined-HP:'进入你的邮箱',
      //   filter box-SC:'全球',
      //   button-su:'免费加入',
      //   header-myearnings:'购买',
      //   button-rf:'用户名',
      //   copy-myearningsvip:'帮助20位朋友成为VIP会员，即可获得20% VIP现金返还。',
      //   box-rf:'邀请你的朋友',
      //   copy-myearningsvip:'你有资格得到10%的现金返还',
      //   header-hc:'获得额外奖励?',
      //   header-myearningsrf:'现金支付',
      //   field-su:'社交传媒',
      //   copy-rf:'要收到你的推荐奖金，你推荐的人必须赚回25美元或更多的现金',
      //   copyabovefriendshipbonus-friendship-bonus:'你想获得10%的友谊奖金吗?',
      //   undefined-HP:'今日优惠券&优惠',
      //   header-myearningsvipb:'VIP',
      //   filter box-SC:'商店类型',
      //   box-hc:'获得分享的报酬',
>>>>>>> a3f21cdd29268a6c505809260221bfe6442982d3
    },
  },
};
