export default {
  'en-US': {
    data: {
      headermyearningsexchange: 'Current Exchange Rate',
      menuHPcashbackworks: 'HOW CASH BACK WORKS',
      HPcategories: 'CATEGORIES',
      filterboxSCflatrate: 'Flat Rate',
      HPfriendsshopping: 'Friends Shopping Network',
      headermyearningsrfreferralbonus: 'Referral Bonus',
      headermyearningsreward: 'You will receive $5 and 5 TLC when you save $25 in paid Cash Back.',
      filterboxSCcashback: 'Cash Back %',
      HPselectcountry: 'Select Country',
      booknow: 'BOOK NOW',
      headercusubtitle: 'Have feedback or need some help?',
      filterboxSCdealtype: 'DEAL TYPE',
      HPbrands: 'BRANDS',
      headermyearningsrfpotentialtlc: 'Potential TLC Reward',
      formcumessage: 'Message',
      filterboxSCsalesoffer: 'Sales Offers',
      headermyearningsrffriendsnetwork: 'YOUR FRIENDS NETWORK',
      sortmenuSCall: 'All',
      copymyearningsvipcontent:
        'You are a VIP10 Member and qualify to receive 10% …receive bonuses of your Cash Back and TLC Reward.',
      fieldsufriend: 'Friend',
      HPfashion: 'Fashion',
      headerhcearnextra: 'EARN EXTRA REWARDS',
      headermyearningspaid: 'Paid',
      copysuprivacypolicy: 'I agree to the Terms & Conditions and Privacy Policy.',
      HPbecomevip: 'Become A VIP',
      headermyearningspending: 'Pending',
      fieldlpenterpassword: 'Enter password',
      headermyearningsviporderid: 'Order ID',
      sortmenuSCcoupons: 'Coupons',
      headermyearningsvipbupgradedate: 'VIP Upgrade Date',
      HPdealscashback: 'Discover Even More Deals With Cash Back',
      headermyearningsfriendshipbonus: 'FRIENDSHIP BONUS',
      HPfooterpopularlinks: 'POPULAR LINKS',
      headermyearningsvipbvipbonus: 'VIP Bonus',
      HPshopnow: 'SHOP NOW',
      headermyearningsviptlcreward: 'TLC REWARD',
      buttonlplogin: 'LOGIN',
      buttonvb: 'JOIN VIP REWARDS TODAY',
      sortbymenuSC: 'Sort By',
      headerhcwhatiscashback: 'WHAT IS CASH BACK?',
      copyrfsharereferral: 'Share your referral link below',
      headermyearningsrfcashbackpending: 'Cash Back Pending',
      copyabovefriendshipbonusfriendshipbonus52: 'Friendship Bonus Tier 5%',
      headermyearnings: 'You have qualified for a Welcome Gift',
      headermyearningsvipqualifiedwelcomegift: 'Name',
      copyabovefriendshipbonusfriendshipbonus2: 'You qualify for 20% Friendship Bonus',
      headercusubheading: 'Have feedback or need some help?',
      headermyearningsvipbusername: 'Username',
      headermyearningswelcomegift: 'WELCOME GIFT',
      HPfinance: 'Finance',
      copymyearningsvip5: 'You Qualify for 5% VIP Cash Back',
      headercuintouch: 'GET IN TOUCH',
      headermyearningsvipdeclined: 'Declined',
      copymyearningsvipbcontent:
        'You will receive $5 and 5 TLC when your referred f… limit to the amount of VIP Bonuses you can earn.',
      filterboxSCtlcdeal: 'TLC Deal',
      headermyearningsvippaid: 'Paid',
      headermyearningsname: 'Name',
      fieldlpenterusername: 'Enter username',
      copyrfsendusername: 'Send your username',
      buttonrfusername6degree: 'username.6Degrees.CASH',
      copyabovefriendshipbonusfriendshipbonus1: 'You qualify for 10% Friendship Bonus',
      copymyearningsrf5:
        'You will receive $5 and 5 TLC for helping your fri…f Referral Bonuses you can earn.  Keep Referring!',
      BannerSC: 'SHOP CATEGORIES',
      fieldsu2name: 'name',
      copylpforgotpassword: 'Forgot Password',
      copymyearningsvip20: 'Do you want to qualify for 20% VIP Cash Back?',
      copyabovefriendshipbonusfriendshipbonus10member:
        'You are a VIP10 Member and qualify to receive 10% …ip Bonus up to 6 Degrees of your friends network.',
      copyabovefriendshipbonusfriendshipbonusearningcalculator: 'Earning Calculator',
      fieldsu2username: 'username',
      fieldsuselecvt: 'Select',
      headermyearningsreferealbonus: 'REFERRAL BONUS',
      headermyearningsrfsignups: 'Signups',
      HPseeall: 'SEE ALL',
      copylp: 'Enter your personal details to begin earning CashBack.',
      copyabovefriendshipbonusfriendshipbonus20:
        'Help twenty friends to become VIP Members and you qualify for 20% Friendship Bonus.',
      HPcashbackoffers: 'CASH BACK OFFERS',
      boxhcbonusprogram: 'Refer A Friend Bonus Program',
      headermyearningsrffrineds: 'Friends',
      copyrfreferafriend:
        'Refer a Friend is to be used for recommending 6Deg…ctronic communications if you have their consent.',
      copymyearningsvipvip20:
        'You are a VIP20 Member and qualify to receive 20% …receive bonuses of your Cash Back and TLC Reward.',
      copyabovefriendshipbonusfriendshipbonusteamdetails: 'Team Details',
      headermyearningsvippending: 'Pending',
      headermyearningsvipbonus: 'VIP BONUS',
      HPcode: 'CODE',
      headermyearningsvipfilter: 'FILTER',
      copyabovefriendshipbonusfriendshipbonustotalfriends: 'Total Friends Team',
      copyabovefriendshipbonusfriendshipbonus5: 'You qualify for 5% Friendship Bonus',
      headermyearningsoffernumber: 'Offer #',
      menuHPshopcategories: 'SHOP CATEGORIES',
      boxrf$5:
        'You will receive $5 and 10 TLC for helping your fr…his Referral Bonus, keep spreading the good word.',
      menuHPcapsrefer: 'REFER A FRIEND',
      headermyearningsrftermsconditions: 'Terms & Conditions Apply *',
      headermyearningsvipbtlcreward: 'TLC Reward',
      filterboxSCfeaturedmarchant: 'Fetaured Deals',
      HPsearchbystore: 'Search by Store',
      filterboxSConline: 'Online',
      headermyearningsvipviptier: 'VIP Tier',
      boxhcshop: 'Shop',
      headermyearningsvipmerchant: 'MERCHANT',
      HPtravel: 'Travel',
      copyrfshareonsocialmedia: 'Share on Social Media',
      HPelectronics: 'Electronics',
      copyabovefriendshipbonusfriendshipbonuspaid: 'Total Friendship Bonus Paid',
      headermyearningsvipbtermsconditions: 'Terms & Conditions Apply *',
      copysu2username: 'username',
      headermyearningsvipvipcashback: 'VIP CASH BACK',
      copymyearningsvip20: 'You Qualify for 20% Cash Back',
      HPjoinfree: 'JOIN FREE',
      headermyearningspaymentperiod: 'Payment Period',
      filterboxSCsericearea: 'SERVICE AREA',
      boxhcreferbonusprogram: 'Refer A Friend Bonus Program',
      headerrf: 'THREE WAYS FOR YOU TO HELP YOUR FRIENDS SAVE MONEY',
      menuHPmyaccount: 'MY ACCOUNT',
      sortmenuSCcashbacktlc: 'CASH BACK + TLC',
      headermyearningsvipbsignups: 'Signups',
      copymyearningsrf:
        'Track the Cash Back performance of your friends. C…elp them save while earning your Referral Bonuses',
      headerlp: 'Hello Friend!',
      filterboxSCselectcountry: 'Select Country',
      HPhotdeals: 'TLC DEALS',
      headermyearningsrftlcreward: 'TLC Reward',
      copyabovefriendshipbonusfriendshipbonusyouareavip:
        'You are a VIP Member and qualify to receive 5% Fri…ip Bonus up to 6 Degrees of your friends network.',
      copyabovefriendshipbonusmyearningsvipb:
        'Track the VIP Upgrade status of your friends. Cont…em unlock VIP Benefits while earning VIP Bonuses.',
      copysu: 'How did you hear about us?',
      headermyearningsdeclined: 'Declined',
      headermyearningsvipcashback: 'CASH BACK',
      headermyearningsfilter: 'FILTER',
      sortmenuSCCashBack: 'CASH BACK',
      headermyearningssortby: 'SORT BY',
      headermyearningsvipoffernumber: 'Offer Number',
      formcu: 'NAME',
      headermyearningsvipbyourfriendsnetwork: 'YOUR FRIENDS NETWORK',
      headermyearningsvipbpotemtialtlc: 'Potential TLC Reward',
      headermyearningsrfpotentialreferalbonus: 'Potential Referral Bonus',
      boxrftrack:
        'You can track invitations and savings performance … Go to My Account > My Earnings > Referral Bonus.',
      boxhcbrowse: 'Browse',
      copysu2: 'My friend who referred me',
      headermyearningstlcreward: 'TLC REWARD',
      HPreferafriend: 'Refer A Friend',
      filterboxSCexlusiveoffers: 'Exclusive Offers',
      headermyearningsdate: 'DATE',
      copyabovefriendshipbonusfriendshipbonusqualify20:
        'Do you want to qualify for 20% Friendship Bonus?',
      fieldsuchooseusername: 'Choose username',
      headermyearningsrfjoindate: 'Join Date',
      boxrf$100:
        'Help your friends join 6Degrees free of cost and s…oney. On average one may save over $100 per year.',
      copymyearningsvip:
        'You are a VIP Member and qualify to receive 5% VIP…receive bonuses of your Cash Back and TLC Reward.',
      headermyearningsvipoverview: 'OVERVIEW',
      headermyearningsterms: 'Terms & Conditions',
      menuHP: 'VIP EVENTS',
      copymyearningsvipvipmember:
        'You are a VIP Member and qualify to receive 5% VIP…receive bonuses of your Cash Back and TLC Reward.',
      copyabovefriendshipbonusfriendshipbonus10:
        'Help ten friends to become VIP Members and you qualify for 10% Friendship Bonus.',
      bannerrf: 'Help Your Friends Save And You Get A $5 Referral Bonus',
      HPnews: 'NEWS',
      headermyearningsvip: 'DATE',
      HPsubscribe: 'SUBSCRIBE NOW',
      headermyearningsvipbpotentialvip: 'Potential VIP Bonus',
      copyabovefriendshipbonusfriendshipbonus:
        'You are a VIP20 Member and qualify to receive 20% …ip Bonus up to 6 Degrees of your friends network.',
      copymyearningsvip10: 'Do you want to qualify for 10% VIP Cash Back?',
      boxhc: 'Earn Cash Back',
      headerhc: 'HOW DOES CASH BACK WORK?',
      fieldsuselectcountry: 'Select Country',
      filterboxSCinstore: 'InStore',
      fieldsu: 'Create Password',
      HPBanner: 'JOIN 6 DEGREES FOR FREE AND GET A $5 BONUS',
      headermyearningsrf: 'OVERVIEW',
      boxrf: 'TRACK PERFORMANCE',
      filterboxSC: 'SPECIAL',
      headermyearningsorderid: 'Order ID',
      headermyearningscashback: 'CASH BACK',
      headermyearningsvipb: 'Friends',
      sortmenuSC: 'Coupons',
      HPhealth: 'Health & Beauty',
      boxrfbonus: 'EARN REFERRAL BONUS',
      formcuemail: 'EMAIL',
      copylpstayloggedin: 'Stay Logged In',
      headermyearningsvipcashback: 'VIP CASH BACK',
      HPenteryouremail: 'Enter Your Email',
      filterboxSCglobal: 'Global',
      buttonsujoinfree: 'JOIN FREE',
      headermyearningspurchase: 'PURCHASE',
      buttonrfusername: 'Username',
      copymyearningsviphelp:
        'Help 20 friends to become VIP Members and you qualify for 20% VIP Cash Back.',
      boxrfinvite: 'INVITE YOUR FRIENDS',
      copymyearningsvipqualify: 'You Qualify for 10% Cash Back',
      headerhcearnextra: 'EARN EXTRA REWARDS',
      headermyearningsrfcashbackpaid: 'Cash Back Paid',
      fieldsusocialmedia: 'Social Media',
      copyrfrefreal:
        'To receive your Referral Bonus, the person you have referred must earn $25 payable cash back or more',
      copyabovefriendshipbonusfriendshipbonus: 'Do you want to qualify for 10% Friendship Bonus?',
      HPtitletopcoupons: 'Select Deals',
      headermyearningsvipbvip: 'VIP',
      filterboxSCmerchant: 'MERCHANT TYPE',
      boxhcgetpaid: 'GET PAID TO SHARE',
      welcomepackage: 'Welcome package',
      myearnings: 'My Earnings',
      welcomeGiftmessage: 'You will receive $5 and 5 TLC when you have $25 in paid Cash Back',
      total: 'Total',
      rfbonustext:
        'You will receive $5 and 5 TLC for helping your friends save $25 in paid Cash Back. There is no limit to the amount of Referral Bonuses you can earn.  Keep Referring!',
      trackrftext:
        'Track the Cash Back performance of your friends. Contact your friends who have not yet started earning Cash Back to help them save while earning your Referral Bonuses',
      rfb5:
        'You are a VIP Member and qualify to receive 5% Friendship Bonus up to 6 Degrees of your friends network.',
      fbpending: 'Friendship Bonus Pending',
      fbpaid: 'Friendship Bonus Paid',
      invitefriend:
        'Help your friends join 6Degrees free of cost and start saving money. On average one may save over $100 per year.',
      trackperfomance:
        'You can track invitations and savings performance of your friends. Go to My Account > My Earnings > Referral Bonus.',
      earnrb:
        'You will receive $5 and 10 TLC for helping your friends save $25. There is no limit to this Referral Bonus, keep spreading the good word.',
      toreceivebonus:
        'To receive your Referral Bonus, the person you have referred must earn $25 payable cash back or more',
      socialText:
        'Refer a Friend is to be used for recommending 6Degrees.CASH to people you know. You should only contact people via email or other electronic communications if you have their consent.',
      vipbanner: 'Unlock a World of Possibilities',
      enjoyVip: 'Enjoy Extra Benefits as a VIP!',
      vipdesc:
        'Upgrading to VIP Membership unlocks three VIP Benefits for you. As a VIP Member you save more money with VIP Cash Back. Get VIP Bonuses when your friends upgrade to VIP and receive Friendship Bonuses when your friends and their friends save money shopping.',
      blueText: 'All these benefits for only $25!',
      footerDesc:
        '6Degrees is a unique opportunity predominently designed for two key groups. Shoppers & Savers and Passive Income Earners.',
      signUp: 'Join Now',
      signIn: 'Sign In',
      loginText: 'Enter your personal details and start journey with us',
      to: 'to',
      login: 'LogIn',
      welcome: 'Welcome Back',
      limited: 'Limited',
      offer: 'Offer',
      period: 'Period',
      mostused: 'MOST USED',
      recharge: 'RECHARGE',
      food: 'FOOD',
      travel: 'TRAVEL',
      fashion: 'FASHION',
      electronic: 'ELECTRONIC',
      cashbacktext:
        'When you shop at thousands of the worlds most popular brands through 6degree.CASH we simply give you back a percentage of your spend once purchase is confirmed',
      dummytext: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
      step1: 'Step 1',
      step2: 'Step 2',
      step3: 'Step 3',
      step4: 'Step 4',
      affiliatesale: 'Affiliate get a commision you get a SALE!',
      affiliatewebsite: 'Affiliate puts your add on their website',
      affiliatecustome: 'Customer clicks & converts',
      affiliatetrack: 'Conversions Are Tracked',
      vipbenefits: ' VIP Benefits',
      featuredbrands: 'Feature Brands',
      featuretext: 'Earn Even More Cash Back on Brands You Love',
      extravip: 'Extra 2% Vip',
      extraviptext: 'Cash Back on 30+ categories',
      flexible: 'Flexible Payment Options',
      traveltext: 'Up to 60% off your hotel stay plus 6% Cash Back',
      welcomeback: 'Welcome Back',
      welcometext: 'to keep connected with us please login with your personal info',
      passwordText:
        'Password must contain at least 8 characters. One upper case, lower case, number and special characters [!,@,%,*].',
      agressterm: ' I agree to terms & conditions and privacy policy.',
    },
  },
  'zh-CN': {
    data: {
      login: '登录',
      to: '至',
      headermyearningsexchange: '当前的汇率',
      menuHPcashbackworks: '返现如何使用',
      HPcategories: '类别',
      filterboxSCflatrate: '平率',
      HPfriendsshopping: '好友网络购物',
      headermyearningsrfreferralbonus: '推荐奖金',
      headermyearningsreward: '您将收到5元和5 TLC当您节省25元现金回来。',
      filterboxSCcashback: '返现%',
      HPselectcountry: '选择国家',
      booknow: '有反馈还是需要帮助?',
      headercusubtitle: '交易类型',
      filterboxSCdealtype: '品牌',
      HPbrands: '潜在的TLC奖励',
      headermyearningsrfpotentialtlc: '消息',
      formcumessage: '销售提供',
      filterboxSCsalesoffer: '你的朋友网络',
      headermyearningsrffriendsnetwork: '所有',
      sortmenuSCall:
        '您是VIP会员，并有资格获得10%的VIP现金返还。继续存钱，你将继续收到现金返还和TLC奖励的奖金。',
      copymyearningsvipcontent: '朋友',
      fieldsufriend: '时尚',
      HPfashion: '获得额外奖励?',
      headerhcearnextra: '已付款',
      copysuprivacypolicy: '本人同意有关条款及细则及私隐政策。',
      HPbecomevip: '变成一个VIP',
      //    header-myearnings:'待定',
      fieldlpenterpassword: '输入密码',
      headermyearningsviporderid: '订单ID',
      sortmenuSCcoupons: '优惠券',
      headermyearningsvipbupgradedate: 'VIP升级日期',
      HPdealscashback: '发现更多现金返还交易',
      headermyearningsfriendshipbonus: '友谊奖励',
      HPfooterpopularlinks: '流行链接',
      headermyearningsvipbvipbonus: 'VIP奖金',
      HPshopnow: '现在购物',
      headermyearningsviptlcreward: 'TLC奖励',
      buttonlplogin: '登陆',
      buttonvb: '现在加入VIP奖励',
      sortbymenuSC: '排序',
      headerhcwhatiscashback: '什么是现金返还?',
      copyrfsharereferral: '下面分享你的推荐链接',
      headermyearningsrfcashbackpending: '现金等待',
      copyabovefriendshipbonusfriendshipbonus52: '友谊奖励等级5%。',
      headermyearnings: '你有资格得到一份欢迎礼物',
      headermyearningsvipqualifiedwelcomegift: '名字',
      copyabovefriendshipbonusfriendshipbonus1: '你有资格获得20%的友谊奖金',
      headercusubheading: '有反馈还是需要帮助?',
      headermyearningsvipbusername: '用户名',
      headermyearningswelcomegift: '用户名',
      welcomepackage: '欢迎礼包',
      HPfinance: '财务',
      copymyearningsvip5: '您有资格获得5%的VIP现金返还',
      headercuintouch: '取得联系?',
      headermyearningsvipdeclined: '拒绝',
      copymyearningsvipbcontent:
        '当您推荐的朋友升级为VIP会员时，您将获得5美元和5 TLC。您可以获得的VIP奖金数量没有限制',
      filterboxSCtlcdeal: 'TLC交易',
      headermyearningsvippaid: '支付',
      headermyearningsname: '名字',
      fieldlpenterusername: '输入用户名',
      copyrfsendusername: '发送你的用户名',
      buttonrfusername6degree: '用户名.6度.现金',
      copyabovefriendshipbonusfriendshipbonus1: '你有资格获得10%的友谊奖金',
      copymyearningsrf5:
        '您将收到5美元和5 TLC帮助您的朋友节省25美元现金回来。你可以获得的推荐奖金没有限制。保持参考!',
      BannerSC: '商店配别',
      fieldsu2name: '名',
      copylpforgotpassword: '忘记密码',
      copymyearningsvip20: '您想获得20% VIP现金返还的资格吗?',
      copyabovefriendshipbonusfriendshipbonus10member:
        '您是VIP10会员，并有资格获得10%的友谊奖金高达6度您的朋友网络。',
      copyabovefriendshipbonusfriendshipbonusearningcalculator: '收入计算器。',
      fieldsu2username: '用户名',
      fieldsuselecvt: '选择',
      headermyearningsreferealbonus: '推荐奖金',
      headermyearningsrfsignups: '注册',
      HPseeall: '看全部',
      copylp: '输入你的个人信息，开始赚回现金。',
      copyabovefriendshipbonusfriendshipbonus20:
        '帮助二十个朋友成为VIP会员，你就有资格获得20%的友谊奖金。',
      HPcashbackoffers: '返现优惠',
      boxhcbonusprogram: '参考朋友奖励计划',
      headermyearningsrffrineds: '朋友',
      copyrfreferafriend:
        '推荐朋友是用来推荐6度的。把钱给你认识的人。只有在得到他人同意的情况下，你才可以通过电子邮件或其他电子通讯方式与他人联系。',
      copymyearningsvipvip20:
        '您是VIP会员，并有资格获得20% VIP现金返还。继续存钱，你将继续收到现金返还和TLC奖励的奖金。',
      copyabovefriendshipbonusfriendshipbonusteamdetails: '团队细节。',
      headermyearningsvippending: '等待',
      headermyearningsvipbonus: 'VIP奖励',
      HPcode: '代码',
      headermyearningsvipfilter: '过滤器',
      copyabovefriendshipbonusfriendshipbonustotalfriends: '朋友总团队。',
      copyabovefriendshipbonusfriendshipbonus5: '你有资格获得5%的友谊奖金。',
      headermyearningsoffernumber: '优惠#',
      menuHPshopcategories: '商店类别',
      boxrf$5:
        '您将收到5美元和10 TLC帮助您的朋友节省25美元。这是没有限制的推荐奖金，继续传播良好的口碑',
      menuHPcapsrefer: '推荐给一个朋友',
      headermyearningsrftermsconditions: '适用条款及细则*',
      headermyearningsvipbtlcreward: 'TLC奖励',
      filterboxSCfeaturedmarchant: '精选优惠',
      HPsearchbystore: '商店搜索',
      filterboxSConline: '线上',
      headermyearningsvipviptier: 'VIP级别',
      boxhcshop: '商店',
      headermyearningsvipmerchant: '商人',
      HPtravel: '旅游',
      copyrfshareonsocialmedia: '在社交媒体上分享',
      HPelectronics: '电子产品',
      ccopyabovefriendshipbonusfriendshipbonuspaid: '友谊奖金总额。',
      headermyearningsvipbtermsconditions: '适用条款及细则*',
      copysu2username: '用户名',
      headermyearningsvipvipcashback: 'VIP现金返还',
      copymyearningsvip20: '您有资格获得20%的现金返还',
      HPjoinfree: '免费加入',
      headermyearningspaymentperiod: '付款期',
      filterboxSCsericearea: '服务区',
      boxhcreferbonusprogram: '参考朋友奖励计划',
      headerrf: '帮助你的朋友省钱的三种方法',
      menuHPmyaccount: '我的账户',
      sortmenuSCcashbacktlc: '返现+TLC',
      headermyearningsvipbsignups: '注册',
      copymyearningsrf:
        '跟踪你朋友的现金返还表现。联系你的朋友谁还没有开始赚钱回来，以帮助他们节省，同时赚取你的推荐奖金',
      headerlp: '你好朋友！',
      filterboxSCselectcountry: '选择国家',
      HPhotdeals: 'TLC优惠',
      headermyearningsrftlcreward: 'TLC奖励',
      copyabovefriendshipbonusfriendshipbonusyouareavip:
        '您是VIP会员，并有资格获得5%的友谊奖金高达6度您的朋友网络。。',
      copyabovefriendshipbonusmyearningsvipb:
        '跟踪您朋友的VIP升级状态。联系您的朋友谁还没有升级，以帮助他们解锁VIP优惠，同时赚取VIP奖金。',
      copysu: '如何知道我们的？',
      headermyearningsdeclined: '拒绝',
      headermyearningsvipcashback: '现金返还',
      headermyearningsfilter: '过滤器',
      sortmenuSCCashBack: '返现',
      headermyearningssortby: '订单数量',
      formcu: '名字',
      headermyearningsvipbyourfriendsnetwork: '你的朋友网络',
      headermyearningsvipbpotemtialtlc: '潜在的TLC奖励',
      headermyearningsrfpotentialreferalbonus: '潜在的推荐奖金',
      boxrftrack: '你可以跟踪你朋友的邀请和储蓄表现。到我的帐户>我的收入>推荐奖金。',
      boxhcbrowse: '浏览',
      copysu2: '推荐我的那位朋友',
      headermyearningstlcreward: 'TLC奖励',
      HPreferafriend: '推荐一个朋友',
      filterboxSCexlusiveoffers: '独家提供',
      headermyearningsdate: '日期',
      copyabovefriendshipbonusfriendshipbonusqualify20: '你想获得20%的友谊奖金吗?',
      fieldsuchooseusername: '选择用户名',
      headermyearningsrfjoindate: '加入日期',
      boxrf$100: '帮助你的朋友加入6度免费，并开始省钱。平均每人每年可以节省100多美元',
      copymyearningsvip:
        '您是VIP会员，并有资格获得5%的VIP现金返还。继续存钱，你将继续收到现金返还和TLC奖励的奖金。',
      headermyearningsvipoverview: '概述',
      headermyearningsterms: '条款和条件',
      menuHP: 'VIP活动',
      copymyearningsvipvipmember:
        '您是VIP会员，并有资格获得5%的VIP现金返还。继续存钱，你将继续收到现金返还和TLC奖励的奖金。',
      copyabovefriendshipbonusfriendshipbonus10:
        '帮助十个朋友成为VIP会员，你就有资格获得10%的友谊奖金',
      bannerrf: '帮助你的朋友省钱，你就能得到推荐奖金',
      HPnews: '新闻',
      headermyearningsvip: '日期',
      HPsubscribe: '现在订阅',
      headermyearningsvipbpotentialvip: '潜在的VIP奖金',
      copyabovefriendshipbonusfriendshipbonus:
        '您是VIP20会员，并有资格获得20%的友谊奖金高达6度您的朋友网络。',
      copymyearningsvip10: '您想获得10%的VIP现金返还吗?',
      boxhc: '获得现金返还?',
      headerhc: '现金返还是如何运作的?',
      fieldsuselectcountry: '选择国家',
      filterboxSCinstore: '商店内',
      fieldsu: '创建密码',
      HPBanner: '加入6度免费，并获得5美元奖金',
      headermyearningsrf: '概述',
      boxrf: '跟踪性能',
      filterboxSC: '特殊的',
      headermyearningsorderid: '订单ID',
      headermyearningscashback: '现金返还',
      headermyearningsvipb: '朋友',
      sortmenuSC: '优惠券',
      HPhealth: '健康&美容',
      boxrfbonus: '获得推荐奖金',
      formcuemail: '电子邮件',
      copylpstayloggedin: '保持登陆',
      headermyearningsvipcashback: 'VIP现金返还',
      HPenteryouremail: '进入你的邮箱',
      filterboxSCglobal: '全球',
      buttonsujoinfree: '免费加入',
      headermyearningspurchase: '购买',
      buttonrfusername: '用户名',
      copymyearningsviphelp: '帮助20位朋友成为VIP会员，即可获得20% VIP现金返还。',
      boxrfinvite: '邀请你的朋友',
      copymyearningsvipqualify: '你有资格得到10%的现金返还',
      headerhcearnextra: '获得额外奖励?',
      headermyearningsrfcashbackpaid: '现金支付',
      fieldsusocialmedia: '社交传媒',
      copyrfrefreal: '要收到你的推荐奖金，你推荐的人必须赚回25美元或更多的现金',
      copyabovefriendshipbonusfriendshipbonus: '你想获得10%的友谊奖金吗?',
      HPtitletopcoupons: '重点优惠',
      headermyearningsvipbvip: 'VIP',
      filterboxSCmerchant: '商店类型',
      boxhcgetpaid: '获得分享的报酬',
      myearnings: '我的收入',
      headermyearningspending: '待定',
      welcomeGiftmessage: '您将收到5美元和5 TLC帮助您的朋友节省25美元现金回来.',
      total: '总',
      headermyearningspaid: '支付',
      rfbonustext:
        '您将收到5美元和5 TLC帮助您的朋友节省25美元现金回来。你可以获得的推荐奖金没有限制。保持参考!',
      trackrftext:
        '跟踪你朋友的现金返还表现。联系你的朋友谁还没有开始赚钱回来，以帮助他们节省，同时赚取你的推荐奖金',
      headermyearningsvipoffernumber: '订单数量',
      copyabovefriendshipbonusfriendshipbonuspaid: '友谊奖金总额',
      rfb5: '您是VIP会员，并有资格获得5%的友谊奖金高达6度您的朋友网络。',
      rfvip8: '',
      fbpending: '友谊奖金',
      fbpaid: '友谊奖金支付',
      invitefriend: '帮助你的朋友加入6度免费，并开始省钱。平均每人每年可以节省100多美元。',
      trackperfomance: '你可以跟踪你朋友的邀请和储蓄表现。到我的帐户>我的收入>推荐奖金。',
      earnrb:
        '您将收到5美元和10 TLC帮助您的朋友节省25美元。这是没有限制的推荐奖金，继续传播良好的口碑。',
      toreceivebonus: '要收到你的推荐奖金，你推荐的人必须赚回25美元或更多的现金',
      socialText:
        '推荐朋友是用来推荐6度的。把钱给你认识的人。只有在得到他人同意的情况下，你才可以通过电子邮件或其他电子通讯方式与他人联系。',
      vipbanner: '打开一个可能性的世界',
      enjoyVip: '作为VIP享受额外优惠！',
      vipdesc:
        '升级为VIP会员资格可为您带来三项VIP优惠。 作为VIP会员，您可以通过VIP Cash Back节省更多钱。当您的朋友升级到VIP时获得VIP奖励 当你的朋友和他们的朋友省钱购物时，可以获得友谊奖金 当您的朋友升级为VIP并获得贵宾奖金时，获取VIP奖金，当您的朋友和他们的朋友省钱购物时。',
      blueText: '所有这些只需25美元',
      footerDesc: '6Degrees是一个为两个关键群体设计的独特机会。购物者和储蓄者以及被动收入者。',
      signUp: '加入现在',
      signIn: '登入',
      loginText: '输入您的个人详细信息并开始我们的旅程',
      welcome: '欢迎回来',
      limited: '有限',
      offer: '提供',
      period: '期',
      mostused: '最常被使用',
      recharge: '充值',
      food: '餐饮',
      travel: '旅行',
      fashion: '时尚',
      electronic: '电子',
      cashbacktext:
        '当您通过6degree.CASH购买数千个世界上最受欢迎的品牌时，我们就是这么简单确认购买后，您可以支付一定比例的支出',
      dummytext: 'Lorem Ipsum只是印刷和排版行业的虚拟文本',
      step1: '步 1',
      step2: '步 2',
      step3: '步 3',
      step4: '步 4',
      affiliatesale: '会员得到佣金你得到销售！',
      affiliatewebsite: '会员将您的添加内容添加到他们的网站上',
      affiliatecustome: '客户点击和转换',
      affiliatetrack: '转换被跟踪',
      vipbenefits: 'VIP 好处',
      featuredbrands: '推荐品牌',
      featuretext: '在您喜爱的品牌上赚取更多现金',
      extravip: '额外2％的贵宾',
      extraviptext: '现金返还30多个类别',
      flexible: '灵活的付款选项',
      traveltext: '高达60％的酒店住宿加6％现金返还',
      welcomeback: '欢迎回来',
      welcometext: '要与我们保持联系，请使用您的个人信息登录',
      passwordText: ' 密码必须至少包含8个字符.一个大写,小写,数字和特殊字符[!,@,％,*]',
      agressterm: '我同意条款和条件以及隐私政策。',
    },
  },
};
